# Build stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Copy everything (includes PurrLay.Shared, PurrLay.UdpV1, PurrLay.UdpV2)
COPY . .
RUN dotnet publish -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /app .

ENV HOST=+
ENV PORT=8081

EXPOSE ${PORT}
EXPOSE 7777/udp
EXPOSE 7778/udp

ENTRYPOINT ["dotnet", "PurrLay.dll"]
